# Generated by Django 5.2 on 2025-05-09 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blink_count', models.IntegerField(default=0, help_text='깜빡임 횟수 (기존 레코드는 0으로 채움)')),
                ('eyes_closed_time', models.FloatField(default=0.0, help_text='눈 감고 있는 시간(초) (기존 레코드는 0.0으로 채움)')),
                ('zoning_out_time', models.FloatField(default=0.0, help_text='멍 때린 시간(초) (기존 레코드는 0.0으로 채움)')),
                ('present', models.BooleanField(default=True, help_text='사용자가 현재 자리에 있는지 여부')),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_value', models.FloatField(default=0.0, help_text='집중도 값 (0.0 ~ 1.0)')),
                ('timestamp', models.DateTimeField()),
                ('blink_count', models.IntegerField(default=0, help_text='눈 깜빡임 횟수')),
                ('eyes_closed_time', models.FloatField(default=0.0, help_text='눈 감고 있는 시간(초)')),
                ('zoning_out_time', models.FloatField(default=0.0, help_text='멍 때린 시간(초)')),
                ('present', models.BooleanField(default=True, help_text='사용자가 자리에 있었는지 여부')),
            ],
        ),
        migrations.CreateModel(
            name='FaceLostEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration_sec', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
