# Generated by Django 5.2 on 2025-05-23 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceLostEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration_sec', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_lost_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('bpm', models.IntegerField(help_text='심박수 (beats per minute)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PressureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('pressure_value', models.FloatField(help_text='입력 값 (0~10)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressure_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_value', models.FloatField(default=0.0, help_text='집중도 값 (0.0 ~ 1.0)')),
                ('timestamp', models.DateTimeField()),
                ('blink_count', models.IntegerField(default=0, help_text='눈 깜빡임 횟수')),
                ('eyes_closed_time', models.FloatField(default=0.0, help_text='눈 감고 있는 시간(초)')),
                ('zoning_out_time', models.FloatField(default=0.0, help_text='멍 때린 시간(초)')),
                ('present', models.BooleanField(default=True, help_text='사용자가 자리에 있었는지 여부')),
                ('focus_score', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focus.studysession')),
            ],
        ),
        migrations.CreateModel(
            name='FocusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blink_count', models.IntegerField(default=0, help_text='깜빡임 횟수 (기존 레코드는 0으로 채움)')),
                ('eyes_closed_time', models.FloatField(default=0.0, help_text='눈 감고 있는 시간(초) (기존 레코드는 0.0으로 채움)')),
                ('zoning_out_time', models.FloatField(default=0.0, help_text='멍 때린 시간(초) (기존 레코드는 0.0으로 채움)')),
                ('present', models.BooleanField(default=True, help_text='사용자가 현재 자리에 있는지 여부')),
                ('focus_score', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_data', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='focus.studysession')),
            ],
        ),
    ]
