# Generated by Django 5.2 on 2025-05-25 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='session',
            field=models.ForeignKey(blank=True, help_text='어떤 공부 세션 중에 기록된 데이터인지', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='focus.studysession'),
        ),
        migrations.AddField(
            model_name='pressureevent',
            name='session',
            field=models.ForeignKey(blank=True, help_text='어떤 공부 세션 중에 기록된 데이터인지', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pressure_events', to='focus.studysession'),
        ),
        migrations.AlterField(
            model_name='focusdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
