# Generated by Django 5.2 on 2025-05-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('bpm', models.IntegerField(help_text='심박수 (beats per minute)')),
            ],
        ),
        migrations.CreateModel(
            name='PressureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('pressure_value', models.FloatField(help_text='입력 값 (0~10)')),
            ],
        ),
    ]
