# Generated by Django 5.2 on 2025-05-25 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_heartbeat_session_pressureevent_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressureevent',
            name='session',
        ),
        migrations.RemoveField(
            model_name='pressureevent',
            name='user',
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('heart_rate', models.IntegerField(blank=True, help_text='심박수 (beats per minute)', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='압력 값 (0~10)', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='focus.studysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Heartbeat',
        ),
        migrations.DeleteModel(
            name='PressureEvent',
        ),
    ]
