# Generated by Django 5.2 on 2025-07-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0003_remove_pressureevent_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusdata',
            name='score',
            field=models.IntegerField(default=0.0),
        ),
    ]
