# Generated by Django 5.2 on 2025-07-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0004_focusdata_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='success_score',
            field=models.FloatField(blank=True, help_text='(예: 세션 성공도, 세션 길이, 별점 등)', null=True),
        ),
    ]
