# Generated by Django 5.2 on 2025-07-19 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0006_fill_focusdata_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusdata',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_data', to='focus.studysession'),
        ),
    ]
