# Generated by Django 5.2 on 2025-05-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartbeat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pressureevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='FocusData',
        ),
        migrations.DeleteModel(
            name='Heartbeat',
        ),
        migrations.DeleteModel(
            name='PressureEvent',
        ),
        migrations.DeleteModel(
            name='RawData',
        ),
    ]
