# Generated by Django 5.2 on 2025-05-16 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0001_initial'),
        ('users', '0002_remove_heartbeat_user_remove_pressureevent_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='expiring', serialize=False, to='authtoken.token')),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
